# Generated by Django 6.0.4 on 2026-04-26 18:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('radius_meters', models.FloatField()),
                ('visit_count', models.IntegerField()),
                ('avg_arrival_hour', models.FloatField()),
                ('avg_departure_hour', models.FloatField()),
                ('avg_duration_minutes', models.FloatField()),
                ('days_of_week', models.JSONField(default=list)),
                ('label', models.CharField(choices=[('home', 'Home'), ('frequent', 'Frequent'), ('occasional', 'Occasional')], default='frequent', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_count'],
            },
        ),
    ]
