# Generated by Django 6.0.4 on 2026-04-26 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('isolation_forest', 'Isolation Forest'), ('threshold', 'Threshold Baseline')], max_length=30)),
                ('model_path', models.CharField(max_length=255)),
                ('training_points_count', models.IntegerField()),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
    ]
