# Generated by Django 6.0.4 on 2026-04-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_pipeline', '0002_trainedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneRiskCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_lat', models.FloatField()),
                ('grid_lng', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('poi_data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('grid_lat', 'grid_lng')},
            },
        ),
    ]
