# Generated by Django 6.0.4 on 2026-04-26 19:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0002_staypoint_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_score', models.FloatField()),
                ('zone_risk', models.FloatField()),
                ('time_factor', models.FloatField()),
                ('distance_factor', models.FloatField()),
                ('combined_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('caution', 'Caution'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='tracking.locationpoint')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('wandering', 'Wandering'), ('deviation', 'Deviation'), ('unfamiliar', 'Unfamiliar Location'), ('aimless', 'Aimless Movement'), ('sos', 'SOS'), ('general', 'General')], default='general', max_length=30)),
                ('message', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_alerts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_alerts', to=settings.AUTH_USER_MODEL)),
                ('risk_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.riskscore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['patient', '-timestamp'], name='alerts_risk_patient_5c5249_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['caregiver', '-created_at'], name='alerts_aler_caregiv_fe9359_idx'),
        ),
    ]
