# Generated by Django 6.0.4 on 2026-04-26 18:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('speed', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('battery_level', models.IntegerField(default=0)),
                ('heading', models.FloatField(default=0)),
                ('activity_type', models.CharField(blank=True, choices=[('still', 'Still'), ('walking', 'Walking'), ('running', 'Running'), ('in_vehicle', 'In Vehicle'), ('unknown', 'Unknown')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_type', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', '-timestamp'], name='tracking_lo_patient_7c7dff_idx')],
            },
        ),
    ]
