# Generated by Django 6.0.4 on 2026-04-26 18:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('radius_meters', models.FloatField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('duration_minutes', models.FloatField()),
                ('point_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['arrival_time'],
                'indexes': [models.Index(fields=['patient', 'arrival_time'], name='tracking_st_patient_dad2bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('end_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('distance_meters', models.FloatField()),
                ('avg_speed', models.FloatField()),
                ('point_count', models.IntegerField()),
                ('path_to_displacement_ratio', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['patient', 'start_time'], name='tracking_tr_patient_37b42b_idx')],
            },
        ),
    ]
